-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- insert into "Visibility"(value, comment)
-- values
-- ('OrganizationMemberOnly', ''),
-- ('ProjectMemberOnly', ''),
-- ('Public', '');
